-- MVP: справочник продуктов и операции продаж.
-- Все цены хранятся как условные единицы (без валютной конвертации).

create table if not exists products (
  id bigint generated by default as identity primary key,
  code text unique not null,
  category text not null,
  name text not null,
  short_name text,
  unit_price numeric(10,2),
  price_rule text,
  active boolean not null default true
);

create table if not exists sales (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id),
  quantity integer not null default 1 check (quantity > 0),
  unit_price_at_sale numeric(10,2),
  sale_date date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists sales_sale_date_idx on sales(sale_date);
create index if not exists sales_product_date_idx on sales(product_id, sale_date);

-- ВАЖНО: цены/правила взяты из предоставленного справочника и уточнений пользователя.
insert into products (code,category,name,short_name,unit_price,price_rule) values
('prime_year','Прайм год','Сберпрайм год','Прайм год',0.50,'fixed'),
('prime_month','Прайм мес','Сберпрайм месяц','Прайм мес',0.25,'fixed'),
('prime_month_switch','Прайм мес','Сберпрайм месяц (переход с текущей подписки)','Переход с текущей',0.20,'fixed'),
('credit_card','Кк','Кредитная карта','Кк',0.88,'fixed'),
('zls','ЗЛС','ЗЛС','ЗЛС',null,'zls'),
('health','Зд','СберЗдоровье стоимостью 3 599 руб.','Зд',0.37,'health'),
('health_1100','Зд','Дополнительные опции стоимостью 1100 руб.','Опции 1100',0.11,'health_option'),
('health_2200','Зд','Дополнительные опции стоимостью 2200 руб.','Опции 2200',0.22,'health_option'),
('column','Колонка','Колонка SberBoom mini','Колонка',0.25,'fixed'),
('tonometer','Тонометр','Тонометр','Тонометр',0.15,'fixed'),
('own_business','Свое дело','«Свое дело»','Свое дело',0.22,'fixed'),
('pds','ПДС','ПДС','ПДС',1.02,'fixed'),
('ops_internal','ОПС','Перевод ОПС внутренний','Внутренний',0.43,'fixed'),
('ops_external','ОПС','Перевод ОПС внешний','Внешний',1.20,'fixed'),
('pension','Пенс','Перевод пенсии','Пенс',0.62,'fixed'),
('premier','Премьер','СберПремьер','Премьер',0.20,'fixed'),
('legal_ip_qr','ЮЛ','Открытие счета ИП с QR','ИП с QR',1.60,'fixed'),
('legal_ip','ЮЛ','Открытие счета ИП без QR','ИП без QR',1.30,'fixed'),
('legal_ooo','ЮЛ','Открытие счета ООО','ООО',1.30,'fixed'),
('legal_payroll','ЮЛ','Зарплатный проект','Зарплатный проект',1.75,'fixed'),
('legal_registration','ЮЛ','Регистрация ИП/ООО','Регистрация ИП/ООО',0.67,'fixed'),
('legal_token','ЮЛ','Выдача токена','Токен',0.65,'fixed'),
('goskey','Гч','Госключ','Гч',0.10,'fixed'),
('mobile_new','Сим','СберМобайл новый номер','Новый номер',0.20,'fixed'),
('mobile_switch','Сим','СберМобайл переход со своим','Переход со своим',0.55,'fixed'),
('mobile_sim_order','Сим','Выдача симкарты по заказу','SIM по заказу',0.10,'fixed'),
('tariff_update','Обновление тарифа','Обновление тарифа','Обновление тарифа',0.25,'fixed')
on conflict (code) do nothing;

-- Ручные разделы ЗП и Детская пока намеренно не создаются.
-- СберПраво присутствует в отчёте пользователя, но цена отсутствует
-- в предоставленном документе. Добавим её после уточнения.
