-- Подготовка справочника. Цены — условные единицы.
create table if not exists products (
 id bigint generated by default as identity primary key,
 code text unique not null, category text not null, name text not null,
 short_name text, unit_price numeric(10,2), price_rule text not null default 'fixed',
 active boolean not null default true
);

create table if not exists sales (
 id bigint generated by default as identity primary key,
 product_id bigint not null references products(id),
 quantity integer not null default 1 check(quantity>0),
 sale_amount numeric(12,2),
 unit_up numeric(10,2) not null,
 sale_date date not null default current_date,
 created_at timestamptz not null default now()
);

create index if not exists sales_sale_date_idx on sales(sale_date);
